### ISSUE TITLE
你好，我想问一下ffmpeg的安装问题，百度了很多资料，没有遇到跟我一样的问题

### ISSUE THREAD

**Issue by 1135890950** [PrintNow/Make-Funny-Image#3]
系统Centos7.4
用的下面这几条命令：
yum install epel-release -y 
rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro 
rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm 
yum install ffmpeg ffmpeg-devel -y

有以下报错：
Error: Package: ffmpeg-libs-2.6.8-3.el7.nux.x86_64 (nux-dextop)
Requires: libass.so.5()(64bit)
Error: Package: libavdevice-2.6.8-3.el7.nux.x86_64 (nux-dextop)
Requires: libopenal.so.1()(64bit)
Error: Package: ffmpeg-libs-2.6.8-3.el7.nux.x86_64 (nux-dextop)
Requires: libschroedinger-1.0.so.0()(64bit)
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

我是个小白，大致看得懂缺libass、libopenal、libschroedinger这几个东西（也不知道对不对），然后百度了好久都没解决，大佬能不能帮我看一下

**Comment by Redbeanw44602** [comment]
不要使用NUX的源，我也遇到这种问题，换个源即可解决
